services:
  minecraft:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: LATEST
      MEMORY: "4G"
      TZ: America/Sao_Paulo

      # server
      MOTD: "Konputaria"
      MAX_PLAYERS: "5"
      DIFFICULTY: normal
      PVP: "true"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "6"
      LEVEL_SEED: "8465694128627486472"

      # acesso
      ONLINE_MODE: "FALSE"
      ENFORCE_WHITELIST: "TRUE"

      # plugins
      MODRINTH_PROJECTS: "worldedit,viaversion,viabackwards,backuper,simpledeathchest,skinsrestorer"

    volumes:
      - ./data:/data

    ports:
      - "25565:25565"

  minecraft-test:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    network_mode: "service:minecraft"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.20.1
      MEMORY: "2G"
      TZ: America/Sao_Paulo
      MOTD: "test"
      MAX_PLAYERS: "20"
      DIFFICULTY: "1"
      SERVER_PORT: "25566"
      LEVEL_SEED: "2253248897752609366"

      # acesso
      ONLINE_MODE: "FALSE"
      ENFORCE_WHITELIST: "TRUE"

      # plugins
      MODRINTH_PROJECTS: "worldedit,viaversion,viabackwards"
    volumes:
      - ./data-test:/data
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "${PLAYIT_SECRET}"
    network_mode: "service:minecraft"
